import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import { projects, profile } from '../src/data.js';
import { home } from '../src/sections/home.js';
import { caseStudy, chapterTitles } from '../src/sections/case-study.js';
import { caseStudyContent } from '../src/sections/case-study/content.js';
import { sceneConfig } from '../src/scene-config.js';
const root = new URL('../', import.meta.url);
const read = (path) => readFile(new URL(path, root), 'utf8');
const tokens = JSON.parse(await read('src/tokens.json'));
let checks = 0;
const verify = (condition, message) => { assert.ok(condition, message); checks++; };
verify(projects.length === 4 && new Set(projects.map((p) => p.id)).size === 4, 'Four unique project routes');
verify(profile.email === 'romancorach@gmail.com', 'Confirmed email');
verify(profile.github === 'https://github.com/romanvsc', 'Confirmed GitHub');
verify(profile.linkedin === 'https://www.linkedin.com/in/roman-vogel-corach-2998bb31b/', 'Confirmed LinkedIn');
for (const project of projects) verify(project.steps.length === 3 && project.decisions.length === 3, `${project.id}: case content`);
const sourceFiles = (await readdir(new URL('src/', root), { recursive: true })).filter((name) => /\.(js|css)$/.test(name) && name !== 'theme.css').map((name) => `src/${name}`);
for (const file of [...sourceFiles, 'index.html', 'blender/generate-portfolio-core.py']) {
  const content = await read(file);
  verify(!/(?:#[0-9a-f]{3,8}\b|0x[0-9a-f]{6}\b|(?:rgb|hsl|oklch)a?\(\s*[\d.])/i.test(content), `${file}: no literal UI colors`);
  verify(!/(?:color|background|fill|stroke)\s*:\s*(?:white|black|red|green|blue)\b/i.test(content), `${file}: no named UI colors`);
}
const css = await read('src/style.css');
verify(css.includes('.dorito-companion {') && css.includes('bottom: calc(100% - 24px)'), 'Sleeping Dorito rests on the hero line');
verify(!css.includes('.dorito-companion-eye'), 'Sleeping Dorito has no eye animation overlay');
verify(css.includes('font-family: "Rosehot"') && css.includes('/fonts/rosehot-free-version/Rosehot.ttf'), 'Local Rosehot display font configured');
verify(!css.includes('Arial Black'), 'Arial Black removed as display font');
verify((await readFile(new URL('public/fonts/rosehot-free-version/Rosehot.ttf', root))).byteLength > 10000, 'Local Rosehot font asset present');
const publicFontFiles = await readdir(new URL('public/fonts/', root), { recursive: true });
verify(!publicFontFiles.some((name) => /mileast/i.test(name)), 'Mileast assets removed');
const portraitImageRule = css.match(/\.hero-portrait img \{([^}]*)\}/)?.[1] || '';
verify(!portraitImageRule.includes('mask-image:') && !css.includes('roman-silhouette-mask.svg'), 'Portrait restored as an intentional rectangle');
verify(css.includes('.hero-portrait::before') && css.includes('.hero-portrait::after'), 'Portrait editorial background blocks configured');
verify(css.includes('var(--color-canvas-tonal)') && css.includes('paper-grain.webp'), 'Editorial tonal background and subtle paper texture configured');
verify(css.includes('position: fixed') && css.includes('mix-blend-mode: multiply') && css.includes('opacity: .22'), 'Background texture remains static and restrained');
const portraitRule = css.match(/\.hero-portrait \{([^}]*)\}/)?.[1] || '';
verify(!portraitRule.includes('border:') && !portraitRule.includes('box-shadow:'), 'Portrait rectangular frame removed');
for (const [, token] of css.matchAll(/var\(--color-([a-z-]+)\)/g)) verify(token in tokens, `Token exists: ${token}`);
const theme = await read('src/theme.css');
for (const [name, value] of Object.entries(tokens)) verify(theme.includes(`--color-${name}: ${value};`), `Theme synchronized: ${name}`);
const manifest = JSON.parse(await read('public/brand/assets.json'));
verify(manifest.backgrounds?.some((item) => item.id === 'paper-grain' && item.path === '/brand/backgrounds/paper-grain.webp' && item.repeatable && item.dimensions === '768x768'), 'Repeatable paper-grain background is registered');
const paperGrain = await sharp(fileURLToPath(new URL('public/brand/backgrounds/paper-grain.webp', root))).metadata();
verify(paperGrain.format === 'webp' && paperGrain.width === 768 && paperGrain.height === 768, 'Paper-grain asset is an optimized 768px WebP tile');
for (const pose of manifest.poses) {
  const svg = await read(`public${pose.path}`);
  verify(svg.includes('<path') && !svg.includes('<image'), `${pose.pose}: true vector, no embedded raster`);
  verify(svg.includes('viewBox='), `${pose.pose}: scalable viewBox`);
  verify(!/<script|onload=|https?:\/\/(?!www.w3.org)/i.test(svg), `${pose.pose}: no executable or remote content`);
  verify(svg.includes('fill="var(--dorito-'), `${pose.pose}: asset palette tokens`);
}
verify(manifest.companion?.path === '/brand/dorito/dorito-acostado.svg', 'Sleeping Dorito companion manifest');
const companionSvg = await read(`public${manifest.companion.path}`);
verify(companionSvg.includes('<path') && !companionSvg.includes('<image'), 'Sleeping Dorito is vector-only');
verify(companionSvg.includes('viewBox=') && !/<script|onload=|https?:\/\/(?!www.w3.org)/i.test(companionSvg), 'Sleeping Dorito SVG is scalable and safe');
verify(companionSvg.includes('fill="var(--dorito-') && manifest.companion.bytes < 1000000, 'Sleeping Dorito palette and size bounded');
verify(Array.isArray(manifest.stack) && manifest.stack.map((item) => item.pose).join(',') === 'php,javascript,vue,css,sql', 'Five technology illustrations manifest');
for (const scene of manifest.stack) {
  const svg = await read(`public${scene.path}`);
  verify(svg.includes('<path') && !svg.includes('<image'), `${scene.pose}: stack vector, no embedded raster`);
  verify(svg.includes('viewBox='), `${scene.pose}: stack scalable viewBox`);
  verify(!/<script|onload=|https?:\/\/(?!www.w3.org)/i.test(svg), `${scene.pose}: stack safe SVG`);
  verify(svg.includes('fill="var(--dorito-'), `${scene.pose}: stack palette tokens`);
  verify(scene.bytes < 500000, `${scene.pose}: stack SVG bounded`);
}
verify(Array.isArray(manifest.projectIcons) && manifest.projectIcons.map((item) => item.id).join(',') === 'registro-produccion,ipac,gestion-gimnasio,mantenimiento', 'Four project icons manifest');
for (const icon of manifest.projectIcons) {
  const svg = await read(`public${icon.path}`);
  verify(svg.includes('<path') && !svg.includes('<image'), `${icon.id}: project icon vector, no embedded raster`);
  verify(svg.includes('viewBox='), `${icon.id}: project icon scalable viewBox`);
  verify(!svg.includes('M0 0h640v640H0z'), `${icon.id}: project icon transparent canvas`);
  verify(!/<script|onload=|https?:\/\/(?!www.w3.org)/i.test(svg), `${icon.id}: project icon safe SVG`);
  verify(svg.includes('fill="var(--project-icon-'), `${icon.id}: project icon palette tokens`);
  verify(icon.bytes < 1000000, `${icon.id}: project icon bounded`);
}
verify(Array.isArray(manifest.headerIcons) && manifest.headerIcons.map((item) => item.id).join(',') === 'inicio,proyectos,tecnologias,sobre-mi,contacto', 'Five header icons manifest');
for (const icon of manifest.headerIcons) {
  const svg = await read(`public${icon.path}`);
  verify(svg.includes('<path') && !svg.includes('<image'), `${icon.id}: header icon vector, no embedded raster`);
  verify(svg.includes('viewBox='), `${icon.id}: header icon scalable viewBox`);
  verify(!/<rect\b/i.test(svg) && icon.transparent === true, `${icon.id}: header icon transparent canvas`);
  verify(!/<script|onload=|https?:\/\/(?!www.w3.org)/i.test(svg), `${icon.id}: header icon safe SVG`);
  verify(svg.includes('fill="var(--header-icon-'), `${icon.id}: header icon palette tokens`);
  verify(icon.bytes < 50000, `${icon.id}: header icon bounded`);
}
verify(Array.isArray(manifest.technologyIcons) && manifest.technologyIcons.length === 10, 'Ten technology source marks registered');
verify(manifest.technologyIcons.map((item) => item.id).join(',') === 'codeigniter,css,docker,javascript,mysql,php,python,supabase,tailwind,vue', 'Technology icons use individually named sources');
for (const icon of manifest.technologyIcons) {
  const svg = await read(`public${icon.path}`);
  verify(svg.includes('<path') && !svg.includes('<image'), `${icon.id}: technology icon is vector-only`);
  verify(svg.includes('viewBox=') && icon.transparent === true, `${icon.id}: technology icon scales on transparent canvas`);
  verify(!/<rect\b|<script|onload=|https?:\/\/(?!www.w3.org)/i.test(svg), `${icon.id}: transparent technology SVG has no background or executable content`);
  verify(svg.includes('fill="var(--technology-icon-'), `${icon.id}: technology illustration palette is internal`);
  verify(icon.bytes < 100000, `${icon.id}: technology SVG bounded`);
  verify(icon.source === `/brand/project-icons/tech_icons_separated_clean/${icon.id}.png` && icon.technology, `${icon.id}: named individual PNG source is documented`);
  const sourceMetadata = await sharp(fileURLToPath(new URL(`public${icon.source}`, root))).metadata();
  verify(sourceMetadata.format === 'png' && sourceMetadata.hasAlpha === true, `${icon.id}: source PNG retains alpha transparency`);
}
verify((await read('public/brand/roman.svg')).includes('data:image/webp;base64,'), 'Portrait wrapper clearly remains raster');
const glb = await readFile(new URL('public/models/portfolio-studio.glb', root));
verify(glb.readUInt32LE(0) === 0x46546c67, 'Studio GLB header');
const files = await readdir(new URL('dist/assets/', root));
const builtCss = await read(`dist/assets/${files.find((name) => name.endsWith('.css'))}`);
verify(!builtCss.includes('@apply') && !builtCss.includes('@theme'), 'Tailwind compiled, no raw directives');
verify(builtCss.includes('.text-link') && builtCss.includes('--color-brand'), 'Semantic interactive styles built');
verify(projects.map((p) => p.id).join(',') === 'registro,ipac,gimnasio,mantenimiento', 'Approved four routes, IPAC retained');
verify(chapterTitles.length === 5, 'Five case chapters');
const normalizedChapterTitles = chapterTitles.map((title) => title.normalize('NFD').replace(/\p{Diacritic}/gu, '').toLocaleLowerCase('es'));
verify(normalizedChapterTitles.join('|') === 'problema|tecnologias utilizadas|sobre el proyecto|galeria del proyecto|caracteristicas', 'Case chapter titles match the approved order');
for (const project of projects) {
  const html = caseStudy(project);
  verify((html.match(/class="case-chapter(?: |")/g) || []).length === 5, `${project.id}: all five chapters rendered`);
  verify((html.match(/data-case-chapter="/g) || []).length === 5, `${project.id}: five chapter data hooks`);
  verify((html.match(/data-case-nav="/g) || []).length === 5, `${project.id}: five internal navigation links`);
  verify(['problem', 'technologies', 'about', 'gallery', 'features'].every((kind) => html.includes(`case-chapter--${kind}`)), `${project.id}: required chapter order and types`);
  verify(html.indexOf('case-chapter--problem') < html.indexOf('case-chapter--technologies') && html.indexOf('case-chapter--technologies') < html.indexOf('case-chapter--about') && html.indexOf('case-chapter--about') < html.indexOf('case-chapter--gallery') && html.indexOf('case-chapter--gallery') < html.indexOf('case-chapter--features'), `${project.id}: chapters follow approved editorial sequence`);
  verify(html.includes('case-hero') && !html.includes('case-featured-capture'), `${project.id}: editorial cover keeps screenshots in the gallery`);
  verify((html.match(/data-case-gallery/g) || []).length === 1 && (html.match(/data-gallery-item/g) || []).length === 3, `${project.id}: one interactive gallery with three captures`);
  verify(html.includes('<dialog') && html.includes('data-gallery-open') && html.includes('data-gallery-close'), `${project.id}: accessible enlarged image dialog controls`);
  verify(html.includes('data-gallery-prev') && html.includes('disabled>') && html.includes('data-gallery-next'), `${project.id}: gallery navigation has bounded controls`);
  verify(!html.includes('autoplay') && !html.includes('screenshot-card'), `${project.id}: no autoplay or legacy static gallery cards`);
  verify(html.includes('case-architecture-node') && html.includes('case-architecture-arrow'), `${project.id}: project architecture diagram`);
  verify(html.includes('case-feature-status') || project.id !== 'mantenimiento', `${project.id}: implementation status is represented when needed`);
  verify(html.includes('NEXT /'), `${project.id}: next project transition`);
  verify(html.includes('IDENTIDAD VISUAL / NO ES UNA CAPTURA'), `${project.id}: identity visual label`);
  verify(!html.includes('alt="undefined"'), `${project.id}: screenshot alt text resolved`);
  verify(project.theme in tokens && `${project.theme}-soft` in tokens, `${project.id}: theme tokens`);
  verify(Boolean(project.architecture), `${project.id}: documented architecture`);
  verify(project.media.gallery.length === 3 && new Set(project.media.gallery.map(({ src }) => src)).size === 3 && project.media.icon.endsWith('.svg'), `${project.id}: three unique selected captures and project icon`);
  const content = caseStudyContent(project);
  verify(content.technologies.length === project.stack.length, `${project.id}: every stack technology has a role description`);
  const technologyAliases = { Vue: 'Vue.js', 'Vue 3': 'Vue.js', 'Vue.js': 'Vue.js', PHP: 'PHP', Docker: 'Docker', Supabase: 'Supabase', MySQL: 'MySQL', 'MySQL / MariaDB': 'MySQL', 'CodeIgniter 4': 'CodeIgniter' };
  for (const item of content.technologies) {
    verify(!item.icon || manifest.technologyIcons.some((icon) => icon.id === item.icon && icon.technology === technologyAliases[item.name]), `${project.id}: technology icon is confidently associated with ${item.name}`);
    if (item.icon) verify(html.includes(`/brand/technology-icons/${item.icon}.svg`), `${project.id}: mapped technology icon appears on its case page`);
  }
  verify(content.features.length > 0 && !html.includes('PENDIENTE DE DOCUMENTAR'), `${project.id}: features are documented without placeholder claims`);
}
const maintenanceCase = caseStudy(projects.find((project) => project.id === 'mantenimiento'));
verify(maintenanceCase.indexOf('Chatbot Asistente IA') < maintenanceCase.indexOf('Dashboard de Mantenimiento'), 'Mantenimiento chatbot is the first gallery capture');
const registroTechnologies = caseStudyContent(projects.find((project) => project.id === 'registro')).technologies;
verify(registroTechnologies.some(({ name, icon }) => name === 'MySQL' && icon === 'mysql'), 'Registro associates the named MySQL icon');
const maintenanceTechnologies = caseStudyContent(projects.find((project) => project.id === 'mantenimiento')).technologies;
verify(maintenanceTechnologies.some(({ name, icon }) => name === 'CodeIgniter 4' && icon === 'codeigniter') && maintenanceTechnologies.some(({ name, icon }) => name === 'MySQL / MariaDB' && icon === 'mysql'), 'Mantenimiento associates CodeIgniter and MySQL icons');
const maintenanceFeatures = caseStudyContent(projects.find((project) => project.id === 'mantenimiento')).features;
verify(maintenanceFeatures.some(({ status }) => status === 'in-progress') && maintenanceCase.includes('EN DESARROLLO'), 'Maintenance features in progress are explicitly labelled');
const caseStyles = await read('src/style.css');
verify(caseStyles.includes('.case-flow-block {') && caseStyles.includes('overflow-wrap: anywhere'), 'Case problem flow wraps safely without desktop overflow');
verify(caseStyles.includes('.case-chapter--problem { grid-template-columns: minmax(0, 1fr);') && caseStyles.includes('.case-flow-block p { max-width: none;'), 'Case problem flow uses full width and readable body copy');
const caseChapterSource = await read('src/sections/case-study/chapter.js');
verify(caseChapterSource.includes('aria-hidden="true">→</span>') && caseChapterSource.includes('<p>${text}</p>'), 'Case problem flow uses directional arrows and paragraph semantics');
verify(caseStyles.includes('.case-nav { position: sticky;') && caseStyles.includes('grid-template-columns: repeat(3, minmax(0, 1fr))'), 'Case navigation has desktop sticky and mobile layouts');
verify(caseStyles.includes('.case-architecture-support {') && caseStyles.includes('.case-gallery-dialog {'), 'Case architecture and accessible gallery dialog are styled');
verify(caseStyles.includes('.case-gallery-thumb:focus-visible') && caseStyles.includes('.case-gallery-step:disabled'), 'Gallery keyboard focus and endpoint states are visible');
verify(caseStyles.includes('.case-technology-icon') && caseStyles.includes('.case-feature-status.is-in-progress'), 'Technology identities and feature progress have dedicated styles');
verify(caseStyles.includes('.case-gallery { min-width: 0; }') && caseStyles.includes('max-width: 100%') && caseStyles.includes('overflow-x: auto;'), 'Gallery media and thumbnail rail constrain narrow layouts');
const interactionSource = await read('src/components/interactions.js');
verify(interactionSource.includes("gallery.parentElement?.querySelector('[data-gallery-status]')"), 'Gallery status updates from its chapter container');
verify(interactionSource.includes('items[currentIndex].dataset') && interactionSource.includes('dialog.showModal()'), 'Enlarged view opens the currently selected capture');
verify(interactionSource.includes("event.key !== 'ArrowLeft'") && interactionSource.includes('returnFocus?.focus({ preventScroll: true })'), 'Gallery supports keyboard selection and returns focus after closing');
const homepage = home();
const homepageSectionOrder = ['id="inicio"', 'id="proyectos"', 'id="tecnologias"', 'id="sobre-mi"', 'id="contacto"'].map((id) => homepage.indexOf(id));
verify(homepageSectionOrder.every((position, index) => position >= 0 && (!index || position > homepageSectionOrder[index - 1])), 'Homepage follows the approved Inicio → Proyectos → Tecnologías → Sobre mí → Contacto order');
verify((homepage.match(/data-progress-link=/g) || []).length === 5, 'The expandable scene menu renders exactly five direct destinations');
verify(homepage.includes('<dialog class="story-menu" id="story-menu" data-story-menu') && homepage.includes('aria-haspopup="dialog"') && homepage.includes('aria-controls="story-menu"') && homepage.includes('aria-expanded="false"'), 'Story menu has dialog semantics and a stateful trigger');
verify(homepage.includes('data-story-menu-close') && homepage.includes('data-story-nav-link') && homepage.includes('class="story-menu-wordmark"') && homepage.includes('class="story-menu-brand"'), 'Two-zone story menu includes the large RV mark, selectable links, and a close control');
verify(homepage.includes('class="story-scrubber" data-story-scrubber') && homepage.includes('type="range"') && homepage.includes('data-story-slider'), 'Cinematic progress control is a native accessible range slider');
verify(homepage.includes('data-scene-current') && homepage.includes('aria-valuetext="Escena 1 de 5: Inicio"'), 'Slider exposes the current scene to assistive technology');
verify((homepage.match(/data-progress-link=/g) || []).length === 5 && homepage.includes('aria-current="location"'), 'The menu has five destinations and an initial current state');
verify(!homepage.includes('scene-bottom-nav') && !homepage.includes('data-scene-progress'), 'The fixed row of five mobile links and discrete progress bar are removed');
verify((homepage.match(/data-scroll-chapter/g) || []).length === 5, 'Progress chapters point to the five main sections');
verify((homepage.match(/data-story-scene=/g) || []).length === 5, 'Five main chapters share the narrative stage');
verify((homepage.match(/data-story-project=/g) || []).length === 4 && (homepage.match(/data-story-beat=/g) || []).length === 6, 'Four project panels and the about/contact story beats are present');
verify(homepage.includes('data-story-focus="portrait"') && homepage.includes('data-story-focus="maintenance-illustration"') && homepage.includes('data-story-focus="vue-card"') && homepage.includes('data-story-focus="about-phrase"'), 'Narrative transitions declare the approved visual focal points');
verify((homepage.match(/tabindex="-1"/g) || []).length >= 6, 'Scene anchors can receive focus after keyboard navigation');
verify(homepage.includes('ESTUDIANTE DE') && homepage.includes('ANALISTA DE SISTEMAS'), 'Student profile remains explicit');
verify(homepage.includes('class="name-first"') && homepage.includes('class="name-last"') && homepage.includes('hero-portrait'), 'Hero editorial layers retained');
verify(homepage.includes('dorito-companion') && homepage.includes('/brand/dorito/dorito-acostado.svg'), 'Sleeping Dorito companion rendered in hero');
verify(!homepage.includes('dorito-companion-eye'), 'Sleeping Dorito companion has no animated eye layer');
verify(homepage.includes('Hola, soy Dorito, la mascota de Román. Estoy en su portfolio porque lo acompaño en sus tardes de programación.'), 'Sleeping Dorito message exact');
verify(!homepage.includes('Registro Personal'), 'Excluded project absent');
verify((homepage.match(/data-project=/g) || []).length === 4, 'Four editorial project sections');
verify((homepage.match(/project-icons\//g) || []).length === 4, 'Four project icons rendered');
verify((homepage.match(/project-icon-background/g) || []).length === 4, 'Four project icons used as background layer');
verify((homepage.match(/data-project-illustration/g) || []).length === 4, 'Four project identity illustrations rendered');
verify((homepage.match(/project-art-index/g) || []).length === 4, 'Each project illustration is labeled as identity art');
verify(!homepage.includes('art-copy-plate') && !homepage.includes('art-label'), 'Project art has no oversized duplicate slogan layer');
verify((homepage.match(/CAPTURA REAL/g) || []).length === 0, 'Screenshots reserved for project pages');
verify((homepage.match(/\/brand\/technology-icons\//g) || []).length === 4, 'Only the four exact standalone technology marks are used in the orbit');
verify(!homepage.includes('Captura%20de%20pantalla%202026-09-17%20214602.png'), 'Mantenimiento screenshot absent from homepage');
verify(!homepage.includes('screenshot-card') && !homepage.includes('project-screenshot'), 'Homepage contains no screenshot gallery');
verify(!homepage.includes('ILUSTRACIÓN CONCEPTUAL') && !homepage.includes('screenshot-placeholder'), 'Conceptual project visuals replaced');
const technologyIds = [...homepage.matchAll(/data-tech-item="([^"]+)"/g)].map(([, id]) => id);
verify(technologyIds.join(',') === 'php,javascript,vue,css,sql', 'Five technologies render in the approved progressive order');
verify(homepage.includes('class="stack-orbit"') && homepage.includes('/brand/dorito/dorito-acostado.svg'), 'A single floating Dorito anchors the technology orbit');
verify(!homepage.includes('data-stack-journey') && !homepage.includes('data-technology-step'), 'Stack reveals are controlled by the shared narrative timeline, not native-scroll checkpoints');
verify(homepage.includes('Lógica de negocio y aplicaciones del lado del servidor.') && homepage.includes('Comportamiento, estados e interacción en la web.') && homepage.includes('Interfaces por componentes para procesos concretos.') && homepage.includes('Jerarquía, sistemas de tokens y layouts adaptables.') && homepage.includes('Relaciones, consultas y estructura para los datos.'), 'Every technology keeps its function description');
for (const icon of ['php', 'javascript', 'vue', 'css']) verify(homepage.includes(`/brand/technology-icons/${icon}.svg`), `${icon}: exact technology icon mapped`);
verify(!homepage.includes('/brand/technology-icons/mysql.svg'), 'SQL is not mislabeled with the MySQL mark');
verify(!homepage.includes('stack-piece') && !homepage.includes('stack-card') && !homepage.includes('data-stack-toggle') && !homepage.includes('data-stack-rotor'), 'Card and flip structures are removed from Stack');
verify(!homepage.includes('stack-note') && !homepage.includes('Mis fortalezas'), 'Stack heading has no redundant strengths note');
verify(!homepage.includes('work-intro') && !homepage.includes('CUATRO FORMAS DE CONECTAR DATOS Y PERSONAS') && homepage.includes('MÁS EN GITHUB'), 'Projects opens directly on the first project and retains only the discreet GitHub ending');
const stackStyles = await read('src/style.css');
verify(stackStyles.includes('.story-stage--depth > .story-scene') && stackStyles.includes('.story-stage--depth #proyectos'), 'Shared stage and project sub-scenes have dedicated presentation');
verify(stackStyles.includes('.story-stage--depth #inicio,') && stackStyles.includes('.story-stage--depth #contacto') && stackStyles.includes('height: auto !important'), 'Scene shells stay centered and reduced motion restores vertical flow');
verify(!stackStyles.includes('stack-piece') && !stackStyles.includes('stack-flip-control'), 'Previous Stack card styling is removed');
verify(stackStyles.includes('.story-stage--depth .technology-orbit-item--php') && stackStyles.includes('.story-stage--depth .technology-orbit-item--javascript') && stackStyles.includes('.story-stage--depth .technology-orbit-item--vue') && stackStyles.includes('.story-stage--depth .technology-orbit-item--css') && stackStyles.includes('.story-stage--depth .technology-orbit-item--sql'), 'Each technology has a distinct orbit position');
verify(stackStyles.includes('grid-template-columns: repeat(2, minmax(0, 1fr))') && stackStyles.includes('@media (max-width: 820px)') && stackStyles.includes('.technology-orbit-item--vue'), 'Tablet and mobile use a visible editorial technology list');
verify(!stackStyles.includes('.stack-section--mobile-orbit') && stackStyles.includes('.story-stage--slider .technology-orbit-item.is-active'), 'Mobile technology orbit remains inside the slider-driven shared stage');
verify(homepage.includes('</section></div><div class="story-scrubber"') && stackStyles.includes('@media (max-width: 820px) and (min-height: 640px) and (prefers-reduced-motion: no-preference)') && stackStyles.includes('.story-scrubber[data-story-scrubber-mode="slider"] { position: fixed;') && stackStyles.includes('overflow: clip;') && stackStyles.includes('env(safe-area-inset-bottom'), 'Mobile slider stays fixed outside the clipped stage and respects the device safe area');
verify(stackStyles.includes('.story-scrubber input::-webkit-slider-thumb') && stackStyles.includes('.story-scrubber input::-moz-range-thumb') && stackStyles.includes('height: 44px;'), 'Slider offers a large touch target and styled controls across browser engines');
verify(stackStyles.includes('body:has(.home-page) .wordmark { position: fixed;') && stackStyles.includes('.story-menu-links a[aria-current="location"]'), 'RV remains floating and the active scene is visibly marked in the menu');
verify(stackStyles.includes('.story-menu-toggle') && stackStyles.includes('.story-menu-close {') && stackStyles.includes('min-width: 44px; min-height: 44px;') && stackStyles.includes('.story-menu-links a {') && stackStyles.includes('font-size: clamp(2.1rem, 4.5vw, 5.4rem);'), 'Menu controls and large scene links remain keyboard and touch accessible');
verify(stackStyles.includes('.story-menu { position: fixed; inset: 0; width: 100vw;') && stackStyles.includes('grid-template-columns: minmax(0, 1.08fr) minmax(0, .92fr)') && stackStyles.includes('.story-menu-brand {'), 'Menu is a full-screen two-zone overlay, with options opposite the RV identity');
verify(!stackStyles.includes('translate3d(var(--story-menu-width)') && !stackStyles.includes('--story-menu-width'), 'Opening the overlay does not push or resize the scene');
verify(stackStyles.includes('.site-header { position: fixed; inset: 0 0 auto; z-index: 40; height: 0; pointer-events: none; border: 0; background: transparent; }') && !stackStyles.includes('--site-header-height') && !stackStyles.includes('.chapter-progress'), 'Header has no visible band or reserved height and the chapter rail is removed');
verify(stackStyles.includes('dorito-orbit-float 5s ease-in-out infinite') && stackStyles.includes('translateY(-6px)'), 'Dorito has a restrained five-second, six-pixel float only in the active orbit');
verify(stackStyles.includes('.technology-orbit-item.is-compact .technology-orbit-mark { width: 1.8rem; height: 1.8rem; }') && !stackStyles.includes('.technology-orbit-item.is-compact .technology-orbit-mark, .technology-orbit-item.is-compact p { display: none; }'), 'Previously revealed technology icons and names remain visible in the orbit');
verify(stackStyles.includes('@media (prefers-reduced-motion: reduce)') && stackStyles.includes('.story-scrubber { display: none !important; }') && stackStyles.includes('.story-stage--depth .stack-orbit-mascot img { max-height: 24rem !important; animation: none !important; }'), 'Reduced motion removes the slider and floating animation in the static flow');
verify(!homepage.includes('activate-scene') && !homepage.includes('studio-section'), '3D experiment removed from home');
verify((await read('src/components/studio.js')).includes("import('../scene.js')"), 'Three remains a lazy chunk');
verify(sceneConfig.pixelRatioLimit <= 1.5, 'DPR capped');
const layout = await read('src/components/layout.js');
verify(layout.includes('class="wordmark"') && layout.includes('href="/#inicio"') && layout.includes('aria-label="Román Vogel, inicio"'), 'Minimal header keeps the RV mark as the Inicio link');
verify(!layout.includes('header-nav') && !layout.includes('header-edition') && !layout.includes('PORTFOLIO / 2026'), 'Chapter links and edition label are removed from the header');
verify(!layout.includes('height:') && !layout.includes('border') && !layout.includes('background'), 'Header markup adds no band, divider, or height reservation');
verify(interactionSource.includes("storyMenu.showModal()") && interactionSource.includes("storyMenu.addEventListener('close'") && interactionSource.includes('returnFocus?.focus({ preventScroll: true })'), 'Story menu uses native dialog Escape handling and restores focus on close');
verify(interactionSource.includes('data-story-menu-close') && interactionSource.includes('[data-story-nav-link]') && interactionSource.includes('storyMenu.close()'), 'Story menu closes from its control and after destination selection');
verify(interactionSource.includes("import { navigateToStoryAnchor } from '../animations/index.js'") && interactionSource.includes('navigateToStoryAnchor(id)) event.preventDefault()'), 'Menu selection invokes the shared story navigator before the native dialog closes');
verify(!interactionSource.includes("querySelector('.header-nav')") && !interactionSource.includes('scrollIntoView'), 'Legacy header navigation handler is removed');
const animationSource = await read('src/animations/index.js');
verify(!interactionSource.includes('portfolio:story-menu-change') && !animationSource.includes('portfolio:story-menu-change'), 'The fullscreen overlay does not refresh or perturb the pinned stage');
const mainSource = await read('src/main.js');
verify(mainSource.includes('navigateToStoryAnchor(id') && mainSource.includes('scrollIntoView'), 'Direct hash loads resolve to a story state or the static anchor fallback');
verify(animationSource.includes('prefers-reduced-motion: no-preference') && animationSource.includes('conditions.motion'), 'Reduced motion disables narrative GSAP while preserving the static page');
verify(animationSource.includes('technologyTransition = .55') && animationSource.includes('majorTransition = .75') && animationSource.includes('storyDistance = 7 * majorTransition + 4 * technologyTransition'), 'Seven main and four technology transitions map to 7.45 viewport heights');
verify(animationSource.includes('technologyStates = techItems.map') && animationSource.includes('stateAtProgress') && animationSource.includes('storyTimeline.addLabel(`state-${state.label}`, timelinePosition)'), 'Twelve named narrative states support weighted reversible scroll');
verify(animationSource.includes('storyTrigger = ScrollTrigger.create') && animationSource.includes('animation: storyTimeline') && animationSource.includes('labelToScroll'), 'One master timeline drives the chapter and technology anchors');
verify(animationSource.includes('autoAlpha: 1, scale: 1, y: 0') && animationSource.includes('is-revealed') && animationSource.includes('is-compact') && animationSource.includes('data-tech-item'), 'Technology reveals accumulate and retain earlier identifiers');
verify(animationSource.includes('IntersectionObserver') && animationSource.includes('syncSceneNavigation') && animationSource.includes('data-scene-current'), 'Direct menu destinations track the current section in normal-flow mode');
verify(animationSource.includes("mobileScrub: '(max-width: 820px) and (min-height: 640px) and (prefers-reduced-motion: no-preference)'" ) && animationSource.includes("storySlider?.addEventListener('input'") && animationSource.includes('storyTimeline.pause().progress'), 'Mobile slider continuously drives the shared timeline and is omitted for low-height or reduced-motion layouts');
verify(animationSource.includes('const zoomSteps = sliderMode ? [1.08, 1.25, 1.55] : [1.3, 1.8, 2.8]') && animationSource.includes('const incomingScale = sliderMode ? .88 : .65'), 'Mobile slider keeps the depth transition while using a tighter scale range for narrow viewports');
verify(animationSource.includes('const restoreSliderViewport = () =>') && animationSource.includes('stage.scrollTop = 0') && animationSource.includes('window.scrollTo({ top: 0, behavior: \'instant\' })'), 'Direct mobile scene navigation restores the cinematic stage viewport and document position');
verify(animationSource.includes('const initialStateIndex = sliderMode ? (chapterIndices[initialAnchor] ?? 0) : 0') && animationSource.includes('time(stateTimes[initialStateIndex])'), 'Resizing into mobile slider mode preserves the current direct-link scene');
verify(animationSource.includes('storyTimeline.tweenTo(stateTimes[targetIndex]') && animationSource.includes('storySlider.setAttribute(\'aria-valuetext\''), 'Direct scene links tween to their first timeline state and describe it accessibly');
verify(!animationSource.includes('initCompactTechnologyOrbit') && !animationSource.includes('technology-steps') && !animationSource.includes('conditions.compact'), 'Independent mobile Stack scroll checkpoints and zoom triggers are removed');
verify(animationSource.includes("min-width: 1280px) and (min-height: 800px) and (hover: hover) and (pointer: fine) and (prefers-reduced-motion: no-preference)"), 'The pinned narrative activates only on the approved desktop capability range');
verify(animationSource.includes('navigateToStoryAnchor') && animationSource.includes('labelToScroll') && animationSource.includes('storyTimeline.tweenTo') && animationSource.includes("addEventListener('scrollend'") && animationSource.includes(".site-header a[href], .story-menu a[href], .scroll-link[href], .skip-link[href], .site-footer a[href]"), 'RV and overlay menu links navigate to the matching narrative state');
verify(animationSource.includes('const mappedScroll = storyTrigger.start + (stateTimes[targetIndex] / storyTimeline.duration()) * (storyTrigger.end - storyTrigger.start)') && animationSource.includes('const targetScroll = Number.isFinite(labelledScroll)'), 'Desktop chapter navigation has a timeline-to-scroll fallback when label mapping is unavailable');
verify(animationSource.includes('syncSceneNavigation') && animationSource.includes("setAttribute('aria-current', 'location')") && animationSource.includes("addEventListener('popstate'"), 'Scene navigation aria-current and browser history follow the active scene');
verify(!animationSource.includes("addEventListener('wheel'") && !animationSource.includes('wheelEvent.preventDefault') && !animationSource.includes('scroll-snap: mandatory'), 'Native scroll remains reversible and is never intercepted');
verify(!animationSource.includes('pin: stackRow') && !animationSource.includes('pin: true, scrub: .6'), 'Independent Stack/project pins are removed from the homepage narrative');
verify(animationSource.includes('caseGestures') && animationSource.includes('data-case-line'), 'Case Studies use dedicated GSAP gestures and diagram lines');
verify(animationSource.includes('data-case-nav') && animationSource.includes('aria-current'), 'Case navigation tracks the active chapter');
verify(!(await read('src/animations/index.js')).includes('dorito-companion-eye') && !(await read('src/animations/index.js')).includes('blink'), 'Sleeping Dorito eye animation removed');
function luminance(hex) {
  const channels = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255).map((n) => n <= .04045 ? n / 12.92 : ((n + .055) / 1.055) ** 2.4);
  return channels[0] * .2126 + channels[1] * .7152 + channels[2] * .0722;
}
const contrastPairs = [['ink', 'canvas'], ['muted', 'canvas'], ['on-brand', 'brand'], ['accent-ink', 'accent'], ['muted', 'surface'], ['focus', 'canvas'], ['maintenance-signal', 'canvas']];
for (const project of projects) contrastPairs.push([project.theme, `${project.theme}-soft`], ['ink', `${project.theme}-soft`], ['muted', `${project.theme}-soft`]);
for (const [foreground, background] of contrastPairs) {
  const values = [luminance(tokens[foreground]), luminance(tokens[background])].sort((a, b) => b - a);
  const contrast = (values[0] + .05) / (values[1] + .05);
  verify(contrast >= 4.5, `Contrast ${foreground}/${background}: ${contrast.toFixed(2)}`);
  console.log(`Contrast ${foreground}/${background}: ${contrast.toFixed(2)}:1`);
}
console.log(`${checks} assertions passed: tokens, assets, project data, contacts, GLB and compiled CSS.`);
