import { projects, profile } from '../data.js';
import { dorito, doritoCompanion, arrow, external } from '../components/layout.js';
import { projectSection } from './projects.js';

export function hero() {
  return `<section class="hero shell story-scene" id="inicio" tabindex="-1" data-scroll-chapter data-story-scene="inicio" aria-labelledby="hero-title"><div class="hero-topline meta"><span>01 / SYSTEMS × DESIGN × CODE</span><span>PERSONAS / PROCESOS / INTERFACES</span></div><div class="hero-editorial"><h1 id="hero-title"><span class="name-first">ROMÁN</span><span class="name-last">VOGEL<span class="hero-dot">.</span></span></h1><figure class="hero-portrait" data-story-focus="portrait"><img src="/brand/roman.webp" width="720" height="720" fetchpriority="high" alt="Retrato de Román Vogel Corach"></figure><p class="portrait-index meta">RV — 01<br>EL LADO HUMANO<br>DEL CÓDIGO.</p></div><div class="hero-bottom">${doritoCompanion()}<p class="hero-role meta">ESTUDIANTE DE<br>ANALISTA DE SISTEMAS<br><span>& DESARROLLADOR WEB</span></p><p class="hero-claim">Construyo sistemas digitales<br>para problemas del mundo real.</p><a class="scroll-link meta" href="#proyectos">SCROLL <span aria-hidden="true">↓</span></a></div></section>`;
}

const stackItems = [
  ['php', 'PHP', 'BACKEND', 'Lógica de negocio y aplicaciones del lado del servidor.', '/brand/technology-icons/php.svg'],
  ['javascript', 'JavaScript', 'INTERACTION', 'Comportamiento, estados e interacción en la web.', '/brand/technology-icons/javascript.svg'],
  ['vue', 'Vue.js', 'FRONTEND', 'Interfaces por componentes para procesos concretos.', '/brand/technology-icons/vue.svg'],
  ['css', 'CSS', 'UI', 'Jerarquía, sistemas de tokens y layouts adaptables.', '/brand/technology-icons/css.svg'],
  ['sql', 'SQL', 'DATA', 'Relaciones, consultas y estructura para los datos.', null],
];

function stackSection() {
  return `<section class="stack-section section story-scene" id="tecnologias" tabindex="-1" data-scroll-chapter data-story-scene="tecnologias" aria-labelledby="stack-title"><div class="shell"><div class="stack-heading"><div><p class="meta">03 / BUILD WITH</p><h2 id="stack-title">MY <em>STACK.</em></h2></div><p class="stack-heading-note meta">PHP × JAVASCRIPT × VUE.JS × CSS × SQL</p></div><div class="stack-orbit" data-story-focus="vue-card"><div class="stack-orbit-mascot"><img src="/brand/dorito/dorito-acostado.svg" width="440" height="440" alt="Dorito, la mascota de Román, en el centro de la órbita tecnológica" loading="lazy" decoding="async"><span class="stack-orbit-caption meta">DORITO / MASCOTA DEL PORTFOLIO</span></div><ul class="technology-orbit" aria-label="Tecnologías y funciones">${stackItems.map(([id, name, role, description, icon], index) => `<li class="technology-orbit-item technology-orbit-item--${id}" data-tech-item="${id}" data-tech-index="${index}"${id === 'vue' ? ' data-story-focus="vue-card"' : ''}><span class="technology-orbit-meta meta">0${index + 1} / ${role}</span><div class="technology-orbit-heading">${icon ? `<span class="technology-orbit-mark" aria-hidden="true"><img src="${icon}" width="40" height="40" alt="" loading="lazy" decoding="async"></span>` : '<span class="technology-orbit-mark technology-type-mark meta" aria-hidden="true">QUERY</span>'}<h3 id="stack-${id}-title">${name}</h3></div><p>${description}</p></li>`).join('')}</ul></div></div></section>`;
}

function chapterNavigation() {
  const chapters = [['inicio', 'Inicio'], ['proyectos', 'Proyectos'], ['tecnologias', 'Tecnologías'], ['sobre-mi', 'Sobre mí'], ['contacto', 'Contacto']];
  return `<button class="story-menu-toggle meta" type="button" data-story-menu-open aria-haspopup="dialog" aria-controls="story-menu" aria-expanded="false"><span class="story-menu-glyph" aria-hidden="true"><i></i><i></i></span><span>MENÚ</span></button><dialog class="story-menu" id="story-menu" data-story-menu aria-labelledby="story-menu-title"><div class="story-menu-inner"><h2 class="sr-only" id="story-menu-title">Navegación del portfolio</h2><nav class="story-menu-links" aria-label="Secciones del portfolio"><ol>${chapters.map(([id, label], index) => `<li><a href="#${id}" data-progress-link="${id}" data-story-nav-link${index === 0 ? ' aria-current="location"' : ''} aria-label="0${index + 1} / ${label}"><span class="story-menu-number" aria-hidden="true">0${index + 1}</span><span>${label}</span><span class="story-menu-arrow" aria-hidden="true">↗</span></a></li>`).join('')}</ol></nav><div class="story-menu-brand"><button class="story-menu-close meta" type="button" data-story-menu-close aria-label="Cerrar navegación">CERRAR <span aria-hidden="true">×</span></button><a class="story-menu-wordmark" href="/#inicio" data-story-nav-link aria-label="RV, ir a Inicio">RV<span aria-hidden="true">.</span></a><p class="story-menu-signature meta">ROMÁN VOGEL CORACH<br>SYSTEMS × DESIGN × CODE</p></div></div></dialog>`;
}

function storyScrubber() {
  return `<div class="story-scrubber" data-story-scrubber><output class="story-scrubber-current meta" id="story-scrubber-current" data-scene-current>01 / 05 · INICIO</output><label class="sr-only" for="story-scrubber-input">Recorrido cinematográfico</label><input id="story-scrubber-input" type="range" min="0" max="1000" step="1" value="0" data-story-slider aria-label="Recorrido cinematográfico de Inicio a Contacto" aria-describedby="story-scrubber-current" aria-valuetext="Escena 1 de 5: Inicio"></div>`;
}

export function home() {
  const projectSlides = projects.map((project, index) => `<div class="project-slide" data-story-project="${project.id}" data-story-beat="project-${project.id}" data-story-focus="${project.id === 'mantenimiento' ? 'maintenance-illustration' : 'project-illustration'}">${projectSection(project)}</div>`).join('');
  return `<main class="home-page" id="contenido" tabindex="-1">${chapterNavigation()}<div class="story-stage" data-story-stage>${hero()}<section class="projects-scene story-scene" id="proyectos" tabindex="-1" data-scroll-chapter data-story-scene="proyectos" aria-labelledby="work-title"><h2 class="sr-only" id="work-title">Proyectos</h2><span class="work-count meta" aria-hidden="true"><span data-project-counter>01</span> / 04</span><div class="project-slides">${projectSlides}</div><div class="work-outro shell meta"><a class="text-link" href="${profile.github}?tab=repositories" ${external}>MÁS EN GITHUB ${arrow}</a></div></section>${stackSection()}<section class="about-section shell section story-scene" id="sobre-mi" tabindex="-1" data-scroll-chapter data-story-scene="sobre-mi" data-story-beat="tecnologias-sobre-mi" aria-labelledby="about-title"><p class="meta">04 / DETRÁS DEL CÓDIGO</p><h2 id="about-title">Primero entender.<br><span data-story-focus="about-phrase">Después <em>construir.</em></span></h2><div class="about-body"><p class="about-lead">Soy Román Vogel Corach.<br>Estudio Analista de Sistemas.</p><div><p>Me interesa entender cómo se trabaja antes de decidir cómo programarlo. Los procesos, los datos y las personas que van a usar el sistema son el punto de partida.</p><p>Trabajo con problemas reales: registrar una operación, administrar una institución, acompañar un gimnasio o seguir el mantenimiento de una flota. Busco transformar esa complejidad en interfaces claras.</p><p class="meta about-principles">ANÁLISIS + DESARROLLO + PRODUCTO</p></div></div></section><section class="contact-section shell section story-scene" id="contacto" tabindex="-1" data-scroll-chapter data-story-scene="contacto" data-story-beat="sobre-mi-contacto" aria-labelledby="contact-title"><div class="contact-top"><p class="meta">05 / LA PRÓXIMA CONVERSACIÓN</p>${dorito('feliz', '¿Hacemos algo?', 'contact')}</div><h2 id="contact-title">¿TENÉS<br><a href="mailto:${profile.email}">UNA IDEA<span aria-hidden="true">↗</span></a>?</h2><div class="contact-bottom"><a class="contact-email text-link" href="mailto:${profile.email}">${profile.email}</a><div class="contact-links meta"><a class="text-link" href="${profile.github}" ${external}>GITHUB ${arrow}</a><a class="text-link" href="${profile.linkedin}" ${external}>LINKEDIN ${arrow}</a></div></div></section></div>${storyScrubber()}</main>`;
}
