export const profile = {
  github: 'https://github.com/romanvsc',
  email: 'romancorach@gmail.com',
  linkedin: 'https://www.linkedin.com/in/roman-vogel-corach-2998bb31b/',
};

export const projects = [
  {
    id: 'registro',
    displayTitle: 'REGISTRO DE<br>PRODUCCIÓN',
    theme: 'production',
    architecture: 'Interfaz Vue, API FastAPI y persistencia MySQL; Docker como herramienta de despliegue.',
    domain: 'Producción forestal', mark: 'RP', subtitle: 'Registro de operaciones',
    flowTitle: 'Del campo al registro', steps: ['Registrar', 'Validar', 'Consultar'],
    caseTitle: 'Poner orden en la operación de campo.',
    challenge: 'El contexto combina producción, combustible y distintas instancias de operación. El foco está en conservar el contexto de cada registro y hacer consultable la información.',
    decisions: [['Registro operativo', 'Reunir los datos de producción y combustible en un mismo circuito.'], ['Trazabilidad', 'Mantener el contexto necesario para consultar y seguir cada operación.'], ['Separación de capas', 'Una interfaz Vue conectada a una API FastAPI y persistencia MySQL.']],
    fork: true,
    number: '01',
    eyebrow: 'FOREST / OPERATIONS',
    title: 'Registro producción',
    statement: 'Operaciones forestales, convertidas en trazabilidad usable.',
    description:
      'Plataforma full-stack para registrar producción, combustible y operación de campo con una base preparada para múltiples instancias.',
    role: 'Full-stack · producto operativo',
    stack: ['FastAPI', 'Vue', 'MySQL', 'Docker'],
    focus: 'Trazabilidad · campo · idempotencia',
    accent: 'forest',
    repository: 'https://github.com/romanvsc/registro_produccion',
  },
  {
    id: 'ipac',
    displayTitle: 'IPAC',
    theme: 'education',
    architecture: 'Frontend Vue y API Django REST Framework. PostgreSQL figura como previsto en la documentación; no se declara aquí su uso en producción.',
    domain: 'Gestión educativa', mark: 'IP', subtitle: 'Administración y tesorería',
    flowTitle: 'Un circuito administrativo', steps: ['Alumnos', 'Cuotas', 'Pagos'],
    caseTitle: 'Administrar con contexto de sucursal.',
    challenge: 'El sistema conecta alumnos, conceptos cobrables, cuotas y pagos. Los permisos y el contexto de sucursal son parte central de la operación administrativa.',
    decisions: [['Administración', 'Organizar alumnos, carreras y conceptos cobrables.'], ['Tesorería', 'Conectar cuotas, pagos, caja y recibos en el circuito de cobranzas.'], ['Contexto y permisos', 'Distinguir roles y sucursales para mantener el alcance de cada operación.']],
    fork: true,
    number: '02',
    eyebrow: 'EDUCATION / ADMIN',
    title: 'IPAC',
    statement: 'Dos sucursales. Una capa operativa para trabajar como un solo sistema.',
    description:
      'Administración, tesorería y cobranzas para IPAC Posadas y Eldorado, con alumnos, cuotas, caja, pagos, reportes e importaciones.',
    role: 'Full-stack · arquitectura modular',
    stack: ['Django', 'DRF', 'Vue', 'Vite'],
    focus: 'Roles · sucursales · cobranzas',
    accent: 'cobalt',
    repository: 'https://github.com/romanvsc/IPAC',
  },
  {
    id: 'gimnasio',
    displayTitle: 'GESTIÓN<br>GIMNASIO',
    theme: 'wellness',
    architecture: 'PWA Vue 3 construida con Vite, estado con Pinia y servicios conectados a Supabase.',
    domain: 'Gestión de gimnasio', mark: 'GY', subtitle: 'Socios y actividad diaria',
    flowTitle: 'La operación del día a día', steps: ['Socios', 'Planes', 'Accesos'],
    caseTitle: 'Acompañar el ritmo del gimnasio.',
    challenge: 'El trabajo frecuente exige acceder con claridad a socios, planes y pagos. La PWA reúne esos flujos y el control de acceso en una experiencia adaptable.',
    decisions: [['Socios y planes', 'Relacionar la información de socios con sus planes y pagos.'], ['Operación diaria', 'Resolver check-in, control de acceso y movimientos de caja.'], ['Interfaz adaptable', 'Una PWA con Vue, Pinia y Supabase como base del producto.']],
    fork: false,
    number: '03',
    eyebrow: 'WELLNESS / DAILY USE',
    title: 'Gestión gimnasio',
    statement: 'El trabajo diario de un gimnasio, en una interfaz que acompaña el ritmo.',
    description:
      'PWA para socios, pagos, planes, check-in, reportes y caja diaria, diseñada para que la operación frecuente tenga poca fricción.',
    role: 'Frontend · producto conectado',
    stack: ['Vue 3', 'Vite', 'Pinia', 'Supabase'],
    focus: 'Check-in · pagos · responsive',
    accent: 'orange',
    repository: 'https://github.com/romanvsc/gestion_gimnasio',
  },
  {
    id: 'mantenimiento',
    displayTitle: 'MANTENIMIENTO<br>DE CAMIONES',
    theme: 'maintenance',
    architecture: 'Aplicación PHP con CodeIgniter 4 y persistencia MySQL/MariaDB; componentes de interfaz en Vue.js.',
    domain: 'Mantenimiento de flotas', mark: 'MT', subtitle: 'Equipos y órdenes de trabajo',
    flowTitle: 'De la lectura a la intervención', steps: ['Lecturas', 'Alertas', 'Órdenes'],
    caseTitle: 'Seguir el mantenimiento de principio a fin.',
    challenge: 'Una flota reúne equipos, lecturas y vencimientos diferentes. El sistema organiza mantenimiento preventivo y correctivo, con historial y órdenes de trabajo.',
    decisions: [['Equipos y lecturas', 'Conservar el contexto de cada equipo y sus registros de uso.'], ['Prevención', 'Relacionar planes y vencimientos con las intervenciones necesarias.'], ['Historial', 'Seguir órdenes de trabajo, repuestos y auditoría de la operación.']],
    fork: true,
    number: '04',
    eyebrow: 'FLEET / MAINTENANCE',
    title: 'Mantenimiento',
    statement: 'Del kilometraje a la orden de trabajo, sin perder el hilo.',
    description:
      'Sistema para mantenimiento preventivo y correctivo de flotas heterogéneas: equipos, lecturas, vencimientos, órdenes, repuestos y auditoría.',
    role: 'Full-stack · dominio operativo',
    stack: ['PHP', 'CodeIgniter 4', 'Vue.js', 'MySQL'],
    focus: 'Preventivo · historial · alertas',
    accent: 'cyan',
    repository: 'https://github.com/romanvsc/mantenimiento',
  },
];
